### ISSUE TITLE
BINs are incorect or missing.

### ISSUE THREAD

**Issue by basitiyidir** [muhammederdem/credit-card-form#2]
Hi Erdem,

Nice work.

BINs are incorect or missing. You should check.

and ..

TROY (Turkey Credit Cart). You better add it. :)

**Comment by kenkeiter** [comment]
There are some BINs over on my [Skeuocard](https://github.com/kenkeiter/skeuocard) project that you're welcome to grab! Take a look at [this file](https://github.com/kenkeiter/skeuocard/blob/master/javascripts/src/CardProduct.coffee), specifically.

**Comment by muhammederdem** [comment]
Hi @basitiyidir ,
I just added type control for troy cards. you can see on this [https://github.com/muhammederdem/credit-card-form/commit/e1d5acf76ae1b7123508ef2b5cc8d3cd5943b65c](commit);
