### ISSUE TITLE
Uppercase Card Name

### ISSUE THREAD

**Issue by ayhankesicioglu** [muhammederdem/credit-card-form#5]
How can I change cardName input value to uppercase using vuejs or mask?

**Comment by ayhankesicioglu** [comment]
I try this
`<input type="text" name="cc_owner" id="cardName" class="card-input__input" v-model="cardName" v-on:focus="focusInput" v-on:blur="blurInput" data-ref="cardName" autocomplete="off" onkeyup="this.value = this.value.toUpperCase();>`
But last character of cardName isn't change.

**Comment by muhammederdem** [comment]
you can try this. it will work;

`@input="cardName = cardName.toUpperCase()"`

**Comment by ayhankesicioglu** [comment]
Thanks @muhammederdem . It's working. And I add a function for Turkish.
`<input type="text" id="cardName" class="card-input__input" v-model="cardName" @input="cardName = cardName.turkishToUpper()" v-on:focus="focusInput" v-on:blur="blurInput" data-ref="cardName" autocomplete="off">`

...

```
<script type="text/javascript">
String.prototype.turkishToUpper = function(){
  var string = this;
  var letters = { "i": "İ", "ş": "Ş", "ğ": "Ğ", "ü": "Ü", "ö": "Ö", "ç": "Ç", "ı": "I" };
  string = string.replace(/(([iışğüçö]))/g, function(letter){ return letters[letter]; })
  return string.toUpperCase();
}
</script>
```

**Comment by muhammederdem** [comment]
Very nice!
